### ISSUE TITLE
probleem bij functie combineerVoorwaarden

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#101]
Bij 9120 is er een volgende combinatie van voorwaardenID's: '203 OR 2039'

Dat geeft een probleem bij combineerVoorwaarden. De voorwaardeIDs worden immers stapgewijs vervangen door de Status_voorwaardes. Dan krijg je dus bv. 'FALSE | FALSE9' in de eerste stap bij vervanging van 203 door FALSE.  En dat kan niet geëvalueerd worden. Genereert een error bij berekenLSVIbasis.

Analoog probleem bij combineerVerschilscore. Daar worden ID's stapsgewijs vervangen door verschilscores. Maar als (vanaf de tweede stap) de voorwaardeID voorkomt in de verschilscore heb je eveneens een probleem. Bv. '702 AND 88'. stap 1 geeft '0.9885 AND 88'. stap 2 geeft '0.90.265 AND 0.265'. De kans is klein, maar ben het wel al tegen gekomen.

Zie niet meteen een snelle oplossing.

**Comment by hansvancalster** [comment]
Kan je eens testen of het probleem opgelost is als je in  `combineerVoorwaarden` volgende wijziging doet:

lijnen 38 en 39 vervang `gsub` door `sub`
lijn 41 vervang `Formule <- gsub(VoorwaardeID[i], Verschilscore[i], Formule)` door `Formule <- gsub(paste0("^",VoorwaardeID[i],"$"), Verschilscore[i], Formule)`

Dezelfde oplossing kan toegepast worden bij combineerVoorwaarden.

**Comment by ToonHub** [comment]
Werkt niet bij mij. VoorwaardenIDs worden niet vervangen.
Waarom sub in plaats van gsub? Er kunnen meerdere AND's staan in de formule. sub vervangt enkel eerste AND, dacht ik.

Hier een testje om te controleren:

VoorwaardeID = c(203, 2039)
Status <- c(TRUE, FALSE)
Formule <- "203 AND 2039"

check1 <- combinerenVoorwaarden(Formule, VoorwaardeID, Status) == FALSE

VoorwaardeID = c(203, 88)
Verschilscore <- c(0.8825, 0.351)
Formule <- "203 AND 88"

check2 <- combinerenVerschilscore(Formule, VoorwaardeID, Verschilscore) == `min(Verschilscore)`

**Comment by ElsLommelen** [comment]
Ok, ook een creatieve oplossing gevonden voor Verschilscore :)
