### ISSUE TITLE
voorwaarde bedekking éénjarigen + open zand > bedekking meerjarigen

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/LSVI#107]
Eventjes in de groep gooien zodat iedereen kan volgen, commentaar geven en op de hoogte is van de beslissing:
Voor habitattype 2330_dw (versie 3) is er bij eenjarigen de voorwaarde 

> bedekking éénjarigen + open zand > bedekking meerjarigen

Vraag is uiteraard: hoe coderen we dit in de databank?
- eerste logische stap is om er 2 aparte voorwaarden van te maken, die vergeleken worden op basis van >
- bij de eerste voorwaarde zit dan de moeilijkheid dat een soortenlijst (S) en een studielijst (H) samengenomen moeten worden.  Eventjes ter achtergrond: in de databank hebben we eigenlijk al 2 situaties waarbij er zowel een soortenlijst als een studielijst opgegeven is:
    - in combinatie met eender welke AnalyseVariabele (bedekking, aantal, aandeel,...) is de studiegroep een bijkomend selectiecriterium voor de soortengroep, meestal toegepast in de vorm van 'soorten van de kruidlaag' (waarbij 'kruidlaag' de studiegroep is)
    - in combinatie met AnalyseVariabele 'bedekkingLaag' wordt de berekening uitgevoerd op basis van de bedekking van de studiegroep (bv. boomlaag, als deze opgegeven is) **OF** op basis van een soortenlijst (als de bedekking van de studiegroep niet opgegeven is)
    - een logische oplossing voor deze nieuwe situatie zou zijn dat er een AnalyseVariabele 'bedekkingSom' toegevoegd wordt die de bedekkingen van studiegroep (hier open zand) **EN** soortenlijst (hier éénjarigen) optelt.  Rest uiteraard nog de vraag: hoe geraakt dat in de databank?  Hiervoor is het zinvol om eerst te weten hoeveel van die gevallen er zijn, en of dit telkens over open zand gaat.  (@Patrikoosterlynck)
- wat bedekking meerjarigen betreft: dit is 'alle soorten uit de opname - de éénjarigen' en doet denken aan de AnalyseVariabele maxBedekkingExcl, waar gewerkt wordt met een soortenlijst 'alle soorten behalve die vermeld in de soortenlijst'.  Dus door hergebruik van die code (meer bepaald de functie deselecteerKenmerkenInOpname) kan relatief snel een nieuwe AnalyseVariabele 'bedekkingExcl' aangemaakt worden.

Alle feedback op dit voorstel is welkom!

**Comment by Patrikoosterlynck** [comment]
De indicator aandeel éénjarigen + open zand > aandeel meerjarigen komt maar bij één habitat (2330_dw) voor. En dit enkel in de nieuwe LSVI-versie. In versie 2 moest de bedekking eenjarigen >= codominant

**Comment by ElsLommelen** [comment]
En zijn er eventueel andere habitats waar bedekkingen van soorten + open zand samengeteld moeten worden?

**Comment by Patrikoosterlynck** [comment]
Ik zie niet direct gelijkaardige gevallen waarin combinatie dient gemaakt van verschillende types indicatoren nee, maar schiet mij nu niet dood als er toch iets in die trend nog zou opduiken ooit...

**Comment by Patrikoosterlynck** [comment]
Mij is nog niet duidelijke wat ik dan hiervoor in de databank dien te voorzien? Nu zit er enkel bedekking eenjarigen in en verkeerde grenswaarde...

**Comment by ElsLommelen** [comment]
De databank zou in orde moeten zijn, met nieuwe AnalyseVariabelen 'aandeelExcl' en 'aandeelSom', en ik heb al een aanzet gemaakt in de vorm van een nieuwe branch voor dit issue waarin ik de tests al aangepast heb aan deze nieuwe invoer (om te vermijden dat we dit achteraf vergeten):

**Comment by ElsLommelen** [comment]
(idee is dus om dit issue verder uit te werken op de branch 'issue107')

**Comment by ElsLommelen** [comment]
dit zou met soortenlijsten moeten werken (wel enkel op niveau van s4-klassen getest), maar wat nog niet werkt, is als een gebruiker de totale bedekking van de éénjarigen of de meerjarigen ingeeft.

**Comment by ElsLommelen** [comment]
ok als het enkel werkt als (eenjarigen + open zand) ingeschat is, of afzonderlijke soorten en zand

**Comment by ElsLommelen** [comment]
nog even testen of het werkt in andere gevallen
