### ISSUE TITLE
omgaan met NA bij Aggregatiemethode == "RapportageHR"

### ISSUE THREAD

**Issue by ToonSpanhoveINBO** [inbo/LSVI#124]
Een NA voor een indicator hoeft m.i. niet per se tot een NA als einduitspraak te leiden.
Indien de NA indicator 'slechts' een belang = b heeft en er reeds een 'ruime meerderheid' van de indicatoren gunstig of ongunstig zijn, maakt die NA eigenlijk niet uit voor de eindbeoordeling.
Indien de NA indicator zb is, en er is reeds een 'ruime meerderheid' van de indicatoren ongunstig, maakt die NA ook niet meer uit.

**Comment by ToonSpanhoveINBO** [comment]
Zijn er plannen om bovenstaande aan te passen in berekenLSVIbasis? Ik krijg voor heel wat opnames nog nog een NA als einduitspraak, terwijl er wel zekerheid bestaat over de gunstige of ongunstige LSVI.

**Comment by ElsLommelen** [comment]
Ja, het plan is om dit aan te passen, en @ToonHub heeft beloofd om dit te doen.

**Comment by ToonHub** [comment]
OK. Ik probeer er vandaag werk van te maken.

**Comment by ElsLommelen** [comment]
@ToonSpanhoveINBO : @ToonHub heeft net de aanpassingen gemaakt, en ik heb ze goedgekeurd.  Dus als je een nieuwe versie installeert, werkt dit.
