### ISSUE TITLE
ondergrens klasse 'r' en 'ZS'

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#132]
Ondergrens van bedekkingsklasse 'r' en 'ZS' staat momenteel op 0. Hierdoor kan je geen onderscheid maken met 'Afwezig'. En dan geeft de rekenmodule voor 'Afwezig' >= 'ZS'  --> TRUE

De handigste oplossing lijkt mij om ondergrens op 0.001 te zetten.

**Comment by hansvancalster** [comment]
ofwel ervoor zorgen dat de ondergrens niet inclusief is en de bovengrens wel inclusief, dus: 
`] ondergrens, bovengrens]`

dat betekent wellicht dat in het script aanpassingen nodig zijn aan `<, >, >=, <=`?

**Comment by ToonHub** [comment]
Na update LSVI-package blijkt dit toch in orde te zijn. Sorry voor het storen...
