### ISSUE TITLE
auteursnamen bij WetNaamKort

### ISSUE THREAD

**Issue by ToonSpanhoveINBO** [inbo/LSVI#144]
Voor sommige soorten (of enkel ondersoorten?) zijn nog auteursnamen aanwezig, waardoor koppeling obv deze naam niet lukt. 
bv. Luzula multiflora (Ehrh.) Lej. subsp. congesta Subspecies

**Comment by ElsLommelen** [comment]
Wat krijg je als foutmelding?  Welke code heb je ingegeven?  Waar zijn die auteursnamen aanwezig?

Ik heb even getest hoe de rekenmodule bovenstaande soortnaam zou omzetten, en hij lijkt die volledig correct te behandelen:
`library(rgbif)`
`parsenames("Luzula multiflora (Ehrh.) Lej. subsp. congesta Subspecies")$canonicalnamewithmarker`
[1] "Luzula multiflora subsp. congesta"

Diezelfde naam staat ook in de databank (en de databank weet dat het een ondersoort van Luzula multiflora is), dus ik zie op nergens een probleem waardoor die naam niet correct gekoppeld en behandeld zou worden bij de berekening.

Dus graag iets meer concrete info (code, foutmelding,...), want ik snap niet wat het probleem zou kunnen zjin.

**Comment by ToonSpanhoveINBO** [comment]
Dit is geen error, maar eerder een onverwachte inhoud van de tabellen
Ik kwam dit tegen bij een controle van de berekende waarde voor het aantal sleutelsoorten (in vergelijking met het lijstje sleutelsoorten).
Door de gewijzigde lijsten tussen "versie 3.2015" (niet gepubliceerd) en de 'to be' - versie 3 , wou ik eerst nog een check doen of de sleutelsoorten effectief in de lijst staan.

IndicatorSoorten <- geefSoortenlijst(Habitattype = "6230_hmo")

#hier staat Luzula multiflora (Ehrh.) Lej. subsp. congesta in de kolom WetNaamKort

In mijn data staat dit zonder auteurs
> Soortendata_i$Kenmerk
 [1] "Carex panicea"          "Erica tetralix"         "Carex demissa"          "Dactylorhiza maculata" 
 [5] "Polygala serpyllifolia" "Drosera rotundifolia"   "Calluna vulgaris"       "Potentilla erecta"     
 [9] "Juncus squarrosus"    

Ik wou alle soorten selecteren uit mijn lijstje, obv IndicatorSoorten$WetNaamKort:
 
 genoteerde_sleutelsoorten <- 
          Soortendata_i %>%
          dplyr::filter(TypeKenmerk != "Studiegroep") %>%
          dplyr::filter(Waarde != 0 & Waarde != "Afw" & Waarde != "afw" ) %>%
          dplyr::filter(Kenmerk %in% IndicatorSoorten$WetNaamKort) %>%
          dplyr::select(Kenmerk)

Die Luzula multiflora subsp. congesta wordt dus (onverwacht) niet meegenomen...

Het lijkt me handigst als in de kolom WetNaamKort reeds de naam zonder auteurs staat.

**Comment by ElsLommelen** [comment]
Ok, bedankt om me hierop te wijzen.

Ik heb het alvast aangepast in de branch waarin ik aan 't werken ben aan de foutboodschappen.  Deze aanpassing zal over enkele dagen bij de gewone installatie beschikbaar zijn.

Moest je graag direct met deze aangepaste versie willen werken, dan kan je deze branch installeren door bij de installatie '@develop' te vervangen door '@foutboodschappen'.  Voor deze branch 'in ontwikkeling' garandeer ik niet dat alles op elk moment perfect werkt...

**Comment by ToonSpanhoveINBO** [comment]
bedankt, voorlopig heb ik dit opgelost parsenames toe te voegen in mijn script...
