### ISSUE TITLE
mossen tellen niet mee als sleutelsoort in de kruidlaag?

### ISSUE THREAD

**Issue by ToonSpanhoveINBO** [inbo/LSVI#145]
Het lijkt erop dat mossen niet worden meegenomen in de berekening van het aantal sleutelsoorten in de kruidlaag. Mogelijk omdat mossen (althans in mijn opnames) typisch in de moslaag worden genoteerd en er ergens in het script een selectie wordt gemaakt van kruidlaag?
Indien er mossen bij de sleutelsoorten van de kruidlaag zitten, zou de moslaag ook moeten worden meegenomen (denk ik toch)?

**Comment by ElsLommelen** [comment]
Kan je een concreet voorbeeld geven van een habitattype waarbij dit het geval is?  En geef je ook meteen enkele namen van mossen die je ingevoerd had?

**Comment by ToonSpanhoveINBO** [comment]
Voorlopig is probleem enkel gemeld bij 910E0_vo (Sphagnum (genus)) en 7140_meso (verschillende soorten, heb ik zelf nog niet grondig gecheckt).

**Comment by ElsLommelen** [comment]
De vegetatielaag in de databank is aangepast voor 91E0_vo, dus dit probleem zou opgelost moeten zijn.

Laat je nog even weten wat het probleem precies is bij 7140_meso?

**Comment by ElsLommelen** [comment]
@ToonSpanhoveINBO  Heb je nog problemen hiermee, of mag dit issue afgesloten worden?
