### ISSUE TITLE
invoerControleData_soortenKenmerken dubbels

### ISSUE THREAD

**Issue by hansvancalster** [inbo/LSVI#174]
Wanneer er synoniemen zijn in DataSoortenKenmerken, kan dit resulteren in dubbels (tweemaal dezelfde soort in dezelfde vegetatielaag van een opname). Wanneer de functie `invoerControleData_soortenKenmerken()` dit detecteert, geeft dit een error. 

Kan dit gewijzigd worden zodat automatisch in die gevallen deze dubbels geaggregeerd worden (som van de bedekkingen)?

**Comment by hansvancalster** [comment]
De reden waarom een error vervelend is, is dat je meestal voor een hele reeks opnamen de berekening wil doen en de fout zich typisch voordoet in slechts 1 opname. Je krijgt echter geen resultaat terug voor de opnamen waar er geen probleem is.

**Comment by ElsLommelen** [comment]
Ik vind het in dit geval zeer gevaarlijk om een resultaat te geven, omdat er verschillende redenen kunnen zijn voor die dubbels en het resultaat hangt sterk af van die reden.  Mogelijke redenen lijken mij:
- eenzelfde waarneming is per vergissing tweemaal ingegeven (of veroorzaakt door scriptfout) -> zou met distinct opgelost moeten worden
- op het terrein is per vergissing tweemaal de bedekking ingeschat voor een soort -> gebruiker moet kiezen welk record hij wil behouden
- volgens het protocol worden per perceel meerdere kleine plotjes bemonsterd en deze bedekkingen worden op een of andere manier geaggregeerd (gemiddelde?) en deze aggregatie is om een of andere reden niet gebeurd -> gebruiker moet die aggregatie zelf doen, want we kennen het protocol niet

Ik kan me eerlijk gezegd vrij moeilijk een situatie bedenken waarbij de som van de bedekkingen nemen de juiste oplossing zou zijn, dus dit standaard als resultaat geven lijkt me geen goed idee, zelfs niet als je er een warning bij zou geven.  Want een gebruiker kan een warning zeer gemakkelijk negeren en het foute resultaat gebruiken.  Een warning zou ik enkel gebruiken als we ongeveer zeker zijn dat het eindresultaat juist is, een beetje als check naar de gebruiker toe.  (Bv. je hebt een extra voorwaarde toegevoegd maar die hebben we niet gebruikt -> handig dat de gebruiker dit weet en evt. kan checken of dit komt door een typfout, maar behalve een evt. niet berekende voorwaarde is er niks mis met het resultaat.)

Ik zie eigenlijk 2 mogelijkheden voor deze situatie en andere situaties waar de gebruiker een probleem moet herstellen vooraleer er een resultaat berekend kan worden:
- eerst datacontrole uitvoeren en hierbij zo snel mogelijk een error geven zodat de gebruiker direct een boodschap krijgt en de problemen kan herstellen vooraleer de berekeningen uitgevoerd worden (dus de mogelijkheid die er momenteel is voor deze situatie)
- een warning geven, de berekening uitvoeren en voor het betreffende record als resultaat NA geven.  Hierdoor moet de gebruiker dus wachten tot alles berekend is vooraleer hij de warning krijgt, en hij zal die berekening achteraf waarschijnlijk nog eens willen overdoen als het probleem opgelost is, dus dat is 2 keer wachten op de berekening (ofwel z'n script herschrijven om enkel het probleemrecord opnieuw te doen)

Ik ben altijd uitgegaan van het idee dat een gebruiker de volledige dataset op een zo kort mogelijke tijd wil analyseren en dat sluit het meest aan bij de eerste optie, maar als er meer animo is voor de 2de optie, dan wil ik dit gerust aanpassen.

**Comment by hansvancalster** [comment]
Inderdaad, voor de drie redenen die je opsomt is aggregatie van de bedekking voor de dubbels geen goed idee en blijft een error het beste signaal. Maar ik heb het over het geval dat de dubbels het gevolg zijn van synoniemen. Deze synoniemen "ontstaan" denk ik ten gevolge van deze code in `invoerControleData_soortenKenmerken()`:

````
KenmerkenSoort <- Kenmerken %>%
      filter(tolower(.data$TypeKenmerk) == "soort_latijn") %>%
      mutate(
        Canonicalname = berekenCanonicalname(.data$Kenmerk)
      ) %>%
      left_join(
        Taxonlijst %>%
          select(
            .data$Canonicalname, .data$NBNTaxonVersionKey
          ) %>%
          distinct(),
        by = c("Canonicalname")
      ) %>%
      bind_rows(
        Kenmerken %>%
          filter(tolower(.data$TypeKenmerk) == "soort_nl") %>%
          left_join(
            Taxonlijst %>%
              select(
                .data$NedNaam, .data$NBNTaxonVersionKey
              ) %>%
              distinct(),
            by = c("Kenmerk" = "NedNaam")
          )
      )
```` 

Ik denk dat achter deze stap een check nodig is die nagaat of _tgv bovenstaande_ er dubbels (synoniemen) ontstaan zijn en - indien dat zo is - de bedekkingen hiervan gesommeerd worden.  Bij de controle van dubbels wordt er immers (o.a.) gegroepeerd op `.data$NBNTaxonVersionKey` en bovenstaande kan ertoe leiden dat verschillende `.data$Kenmerk` dezelfde `.data$NBNTaxonVersionKey` krijgen.

**Comment by ElsLommelen** [comment]
Euh, zou je even een concreet voorbeeldje kunnen geven waarin dit probleem opduikt?

**Comment by hansvancalster** [comment]
Ik heb het even wat verder getest en kan het probleem nu terugbrengen tot een geval waarbij een soort wordt vertaald naar twee verschillende NBNTaxonVersionKey waardoor een error (wellicht onterecht) getriggerd wordt.

Hier is een reproduceerbaar voorbeeld:
`````
library(LSVI)
maakConnectiePool()

Data_habitat <-
  data.frame(ID = "1",
             Habitattype = "3110")

Data_soortenKenmerken <-
  data.frame(ID = "1",
             Kenmerk = c('Eleocharis palustris (L.) Roem. et Schult.'),
             TypeKenmerk = "soort_latijn",
             Waarde = c(10),
             Type = "Percentage",
             Invoertype = NA,
             Eenheid = "%",
             Vegetatielaag = "kruidlaag")


test <- berekenLSVIbasis(Versie = "Versie 2.0",
                 Kwaliteitsniveau = "1", Data_habitat,
                 Data_voorwaarden, Data_soortenKenmerken)
````

**Comment by ElsLommelen** [comment]
Vreemd, ik krijg geen error als ik die code uitvoer, noch met de laatste versie van de `develop` branch, noch met de branch `dubbelsInDatabank` waarin ik gelijkaardige problemen aan 't oplossen ben (PR #172).  En ook niet als ik connecteer met de SQLite-databank...
Kan je evt. even je session-info doorgeven?  (Of we kunnen het morgen samen bekijken.)

**Comment by ElsLommelen** [comment]
Specifiek voor Eleocharis palustris en Eleocharis uniglumis blijkt het probleem te zijn dat Eleocharis palustris subsp. uniglumis, een junior synoniem van Eleocharis uniglumis, momenteel via rgbif::parsenames() vertaald wordt naar Eleocharis palustris, waardoor E. uniglumis en E. palustris als synoniemen beschouwd worden.  Dit zou opgelost moeten worden door het in gebruik nemen van de functie parseTaxonnaam (issue #33).

Wel testen wat er nu gebeurt als echte synoniemen ingevoerd worden, en ervoor te zorgen dat in dit geval de berekening wel gebeurt met als warning dat de soorten als synoniem beschouwd zijn.  In andere gevallen de error behouden.

**Comment by ElsLommelen** [comment]
@hansvancalster  Ik neem aan dat dit probleem intussen volledig opgelost is en dat dit issue gesloten mag worden?

**Comment by hansvancalster** [comment]
Ja, klopt die problemen ben ik niet meer tegengekomen.
