### ISSUE TITLE
overbodige code in deselecteerKenmerkenInOpname

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/LSVI#181]
@ToonHub: In deselecteerKenmerkenInOpname staat er code om de aanwezigheid van een subAnalyseVariabele op te vangen, maar is deze code wel nodig?  Een subAnalyseVariabele komt normaal gezien enkel bij AnalyseVariabele aantal voor.  Deze code wissen of behouden (en dan zou er best een unittest voor geschreven worden)?

**Comment by ToonHub** [comment]
OK doe maar weg dan
