### ISSUE TITLE
berekenLSVIbasis totaal aantal sleutelsoorten

### ISSUE THREAD

**Issue by hansvancalster** [inbo/LSVI#35]
Het zou interessant zijn indien de functie berekenLSVIbasis ook het totaal aantal sleutelsoorten geeft voor een bepaald habitattype. Deze info is nodig voor een (nog te ontwikkelen) functie voor de berekening van een distance to target.

**Comment by ElsLommelen** [comment]
voorlopig is nSoortenLSVI toegevoegd aan de uitvoer van berekenLSVIbasis, idee is om op termijn de functie distance-to-target op te roepen vanuit berekenLSVIbasis (gelijkaardig aan berekenStatus) en dan deze variabele niet meer uit te voeren

**Comment by ElsLommelen** [comment]
Deze geeft wel altijd het aantal soorten, ongeacht of er een aantal soorten of bedekking berekend is.  Is dit ok, of moet er ingeval van bedekking een andere waarde (bv. NA) ingevoerd worden om te kunnen achterhalen wanneer het over aantallen gaat, @hansvancalster ?

**Comment by hansvancalster** [comment]
Je zou misschien de variabele nSoortenLSVI kunnen hernoemen naar TheoretischMaximum. In geval van aantal soorten komt daar dan het totaal aantal soorten in de lijst. In geval van een bedekking, komt daar dan 100 (%) te staan. In nog andere gevallen kan het dan bijvoorbeeld gaan over het maximaal aantal stadia, structuurlagen, ...

**Comment by ElsLommelen** [comment]
opgelost voor huidige s4-klassen(?)

**Comment by hansvancalster** [comment]
Ik denk dat deze issue gesloten kan worden
