### ISSUE TITLE
vegetatielagen

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/LSVI#36]
er moet nog rekening gehouden worden met de vegetatielagen bij de selectie van de soorten.  Dit moet in de eerste plaats in de databank in orde zijn (studielijst), daarna zorgen dat de ingevoerde soortenlijst ook de vegetatielaag bevat (waar relevant)

**Comment by ElsLommelen** [comment]
voor de is dit opgelost in #63 , databank hieraan aanpassen moet nog gebeuren

**Comment by ElsLommelen** [comment]
Databank zou ook in orde moeten zijn, nog testen of het geheel werkt...

**Comment by ToonHub** [comment]
OK

**Comment by ElsLommelen** [comment]
Ineens werkt dit issue niet meer bij de unittests, en blijkbaar ligt het probleem bij de ETL van de databank.  Op te volgen of dit terug in orde is, issue mag terug dicht als het terug in orde is.  

(Dit geeft bij de check bij de unittest de volgende foutmelding: Failure: berekenLSVIbasis vegetatielaag: de functie geeft een warning of error als een vegetatielaag ontbreekt (@test_berekenLSVIbasis_vegetatielaag.R#223))

**Comment by ElsLommelen** [comment]
Ineens werkt dit issue niet meer bij de unittests, en blijkbaar ligt het probleem bij de ETL van de databank. Op te volgen of dit terug in orde is, issue mag terug dicht als het terug in orde is.

(Dit geeft bij de check bij de unittest de volgende foutmelding: Failure: berekenLSVIbasis vegetatielaag: de functie geeft een warning of error als een vegetatielaag ontbreekt (@test_berekenLSVIbasis_vegetatielaag.R#223))

**Comment by ElsLommelen** [comment]
unittest werkt al een tijdje terug, dus dit zal wel in orde zijn, vermoed ik.
