### ISSUE TITLE
Package DBI wordt niet geladen

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#40]
functie dbGetQuery wordt niet herkend omdat package DBI niet wordt geladen

**Comment by ElsLommelen** [comment]
Heb jij dat package geïnstalleerd op je laptop?  Normaal zou het automatisch moeten laden als je het package LSVI laadt (het staat vermeld in de description-file)

**Comment by ToonHub** [comment]
DBI was al geïnstalleerd. Ik zal kijken of ik de foutmelding nog krijg een volgende keer als ik LSVI-package laad.

**Comment by ElsLommelen** [comment]
@ToonHub  Stelt dit probleem zich nog?  (Kwestie van wat issues op te ruimen ;-) )
