### ISSUE TITLE
Foute TypeVariabele in databank voor habitat 9110

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#42]
Bij 'sleutelsoorten' staat TypeVariabele = Decimaal getal en referentiewaarde = B
Ik vermoed dat dit de oorzaak is van de foutmelding bij functie vertaalInvoerinterval in berekenLSVIBasis:
Error in mutate_impl(.data, dots) : 
  Evaluation error: Niet alle opgegeven getallen zijn numerieke waarden.

De foutboodschap is niet echt duidelijk. Als gebruiker kun je er ook weinig aan veranderen.

**Comment by ElsLommelen** [comment]
Gaat dit over een foute waarde in de databank, of door de gebruiker ingegeven?

**Comment by ToonHub** [comment]
In de databank

**Comment by ElsLommelen** [comment]
aangepast in de databank, zou nu geen probleem meer mogen geven

**Comment by ToonHub** [comment]
OK!
