### ISSUE TITLE
geen min en max waarde voor categorie ZS

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#43]
Habitat 9110 heeft in databank ZS als referentiewaarde voor 'bedekking invasieve exoten kruidlaag'. Maar voor ZS staat er geen min en max waarde in LIJST.

Dit geeft volgende warning:

In vertaalInvoerInterval(Invoervereisten[, c("Rijnr", "TypeVariabele",  :
  Niet voor elke opgegeven categorische variabele is er een numerieke waarde opgenomen in de databank (zie functie vertaalInvoerInterval()), waardoor niet voor elke waarde een berekening gemaakt kan worden. Controleer de spelling van de categorische variabele, of neem contact op met de beheerder van het package om nieuwe numerieke waarden aan te leveren.

**Comment by ElsLommelen** [comment]
Idee is dat je ook waarden aanlevert... ;-)  Maar je hebt geluk: ik had nog een lijstje van Hans en heb me hierop gebaseerd om waarden in te vullen.  Zou in orde moeten zijn?
