### ISSUE TITLE
analysevariabele 'climax- en degeneratiestadium aanwezig'

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#46]
In de databank staat bij voorwaarde 'climax- en degeneratiestadium aanwezig' de analysevariabele 'climax en degeneratiestadium aanwezig'.  Hiervoor is er nog geen klasse aangemaakt. Dus berekenLSVIbasis geeft foutmelding.

**Comment by ElsLommelen** [comment]
Voor de toekomst (dus voor nadat Gert nog eens een run gedaan heeft), kan je dit aanpassen door in de net gedeelde folder aan het bestand Voorwaarde_Analysevariabele.csv aan te vullen (idem voor alle gelijkaardige gevallen).  Ik zal dit nu in de nieuwe databank eventjes aanpassen, zodat je verder kan.

**Comment by ElsLommelen** [comment]
Het zou aangepast moeten zijn...
