### ISSUE TITLE
invasieve exoten ontbreekt voor 4030

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#47]
de indicator invasieve exoten voor 4030 zit niet in de databank

**Comment by ElsLommelen** [comment]
als je naar het resultaat van geefInfoHabitatfiche(Habitattype = "4030", Versie = "Versie 3") kijkt, zie je dat alles van habitat ingevuld is en niks van beoordeling.  Een teken dat er iets mis is bij de koppeling van deze 2 velden.  Nog verder uit te zoeken waarom.

**Comment by ElsLommelen** [comment]
Probleem gelokaliseerd, ik geef het door aan Patrik

**Comment by ElsLommelen** [comment]
De NA-rij bij geefInvoervereisten is een gevolg van dit probleem

**Comment by ElsLommelen** [comment]
in orde (tenminste voor kwaliteitsniveau 1)
