### ISSUE TITLE
indicator 'verbossing' voor 4030 wordt niet weergegeven via geefInvoervereisten

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#48]
geefInvoervereisten geeft wel ID van indicator maar verdere details staan op NA

via berekenLSVIbasis worden wel de correcte gegevens uit de databank gehaald voor deze indicator

**Comment by ElsLommelen** [comment]
Vreemd, bij mij staat de indicator verbossing er wel tussen als ik geefInvoervereisten(Habitattype = "4030", Versie = "Versie 3", Kwaliteitsniveau = 1) ingeef.  (Er staat nog wel een extra lege rij, een nog op te lossen probleem.)  Voorlopig staat er bij bebossing nog geen soortengroep, deze moet nog toegevoegd worden, dus normaal zou de berekening (selectie van soorten) nog niet kunnen gebeuren

**Comment by ToonHub** [comment]
OK staat er bij
