### ISSUE TITLE
Referentiewaarde 'ja' wordt niet gemigreerd

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#52]
bij voorwaarde 'mozaïek met 2330' bij habitat 2310, wordt referentiewaarde 'ja' niet gemigreerd.
Patrik heeft dit wel ingevoerd.

**Comment by ElsLommelen** [comment]
fout doet zich consistent voor bij alle velden waar ja/nee ingevoerd moet worden, en dit heb ik doorgegeven

**Comment by ElsLommelen** [comment]
zou opgelost moeten zijn
