### ISSUE TITLE
indicator horizontale structuur ontbreekt  voor 2330_bu

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#53]
Patrik heeft deze indicator ingevoerd, maar werd niet gemigreerd naar databank

**Comment by ElsLommelen** [comment]
Patrik had deze indicator in de databank op non-actief gezet (= te negeren bij de migratie), ik heb dit aangepast.  Als er nog eens iets ontbreekt, Patrik er even aan helpen denken om dit aanvinkvakje te checken...

**Comment by ElsLommelen** [comment]
Lijkt me in orde te zijn?
