### ISSUE TITLE
studiegroepID ontbreekt bij voorwaarde 'climax of degeneratiestadium' voor 2310	

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#54]
- hierdoor krijg je een error bij berekenWaarde
- het makkelijkste lijkt me een aparte studiegroep aan te maken met enkel climaxstadium en degeneratiestadium --> dan kunnen we klasse 'aantal' gebruiken
- heb nog niet afgtetoets hoe Patrik dit heeft ingegeven

**Comment by ElsLommelen** [comment]
Patrik heeft zo'n studiegroep ingegeven, maar deze indicator heeft een complexe structuur die ik nooit eerder gezien heb: 2 voorwaarden met verschillende lijstjes en zelfs technisch verschillende types van lijstjes.  Het ontbrekende lijstje zit 'verborgen' onder het andere lijstje (4 stadia), en het migratiescript weet niet dat het daar een lijstje moet zoeken (omdat we niet wisten dat dergelijke structuren in de databank ingevoerd zijn)...  Ik geef het door.

**Comment by ToonHub** [comment]
-een alternatieve oplossing: zelfde studiegroep (met 4 stadia) en een aangepaste klasse maken die de aanwezigheid van climaxstadium en degeneratiestadium checkt. Moest dat veel migratieproblemen voorkomen lijkt me dat een aangewezen oplossing.

**Comment by ToonHub** [comment]
OK vergeet tweede optie :-)
