### ISSUE TITLE
taxonlijst voorwaarde 'aantal sleutelsoorten' en 'bedekking sleutelsoorten' bij 7140_oli versie 3 komt er niet door

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#61]
Beide voorwaarde hebben ID voor taxonlijst. Maar de soortenlijst wordt niet gegenereerd bij aanmaken van object (of bij functie geefSoortenlijstVoorIDs)

Weet niet of het aan invoer van soortenlijst door Patrik ligt of aan migratie

**Comment by ElsLommelen** [comment]
Gevonden: foutje in de query die deze gegevens ophaalde...  (Lijst bestaat uit meerdere sublijsten, wat minder vaak voorkomt, en net bij het ophalen van die sublijsten zat een foutje.)

Herstelling zit voorlopig enkel in branch databankTest

**Comment by ElsLommelen** [comment]
zou intussen ook in orde moeten zijn in de develop branch
@ToonHub : check je even en sluit je dan dit issue?

**Comment by ToonHub** [comment]
OK
