### ISSUE TITLE
dubbele selectie van soorten bij vermossing

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#76]
in de lijst van vermossingsoorten zitten heel wat soorten met zelfde nbn-key. Dit zorgt ervoor dat soorten tweemaal geselecteerd worden en bedekking voor indicator wordt overschat. 

Heb code toegevoegd in branch aanpassingenTW die dit moet vermijden. Maar misschien moet de soortenlijst voor vermossing eerder aangepast worden?

**Comment by ElsLommelen** [comment]
Lap, omwille van het feit dat draadwier meermaals voorkomt in de databank (omwille van verschillende naamgevingen die in INBOVEG gebruikt worden), had ik hiervoor vlak voor mijn verlof al een oplossing uitgewerkt, maar deze commit was ik in mijn haast vergeten de pushen voor het accepteren van de pull request hierover.  Ik zal een nieuwe pull request maken met enkel deze ene commit, kan je even kijken of deze oplossing ook voor u voldoet en deze dan aanvaarden.

Ik heb ervoor gekozen om deze aanpassing te doen vlak nadat de gebruiker de soortenlijst ingevoerd heeft en niet bij de berekening van de resultaten, omdat de situatie zich zou kunnen voordoen dat een gebruiker 2 verschillende soortennamen invoert die intussen synoniem van elkaar zijn (maar niet op het moment dat de opname gemaakt is).  In dat geval gaat de rekenmodule aan deze 2 soorten dezelfde nbn-key toekennen (hij neemt de key van wat nu aanvaard is als soort), maar vermits de gebruiker ze als verschillende soorten beschouwd heeft, moeten de bedekkingen in dat geval wel degelijk 'opgeteld' worden.

In het geval dat in de databank tweemaal dezelfde Latijnse naam voorkomt omdat er verschillende Nederlandse namen opgenomen zijn, of omgekeerd, moet er uiteraard wel voor gezorgd worden dat die dubbels eruit gehaald worden, en dat is wat de door mij voorgestelde oplossing doet.

**Comment by ElsLommelen** [comment]
@ToonHub   Opgelost?  Dan graag even sluiten.

**Comment by ToonHub** [comment]
OK
