### ISSUE TITLE
hoe omgaan met al dan niet aangeven van lagen?

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/LSVI#90]
Ik heb ons alledrie toegevoegd, omdat ik dit item eerst wil bediscussiëren.  Het inwerken wil ik evt. wel doen.

Naar aanleiding van pull request #85 merkte ik bij een van de testen een probleem: ik had een opname met tamelijk wat eik, maar de berekening gaf 0 % aan.  Na wat zoeken bleek dat het probleem lag bij het feit dat ik niet gespecifieerd had dat die eik in de boomlaag stond.  Ok, eigenlijk een foutje van mijn kant, maar het verontrustende vind ik dat hier nergens een waarschuwing voor gegeven wordt.  Een gebruiker kan bij Vegetatielaag NA ingeven, maar zonder dat hij het merkt, wordt de soort in kwestie genegeerd bij de berekeningen.

Dit zou naar mijn gevoel anders moeten.  Hoe dit oplossen?

Ik heb alvast enkele ideeën op een rijtje gezet:
- Vegetatielaag verplicht invullen voor alle soorten in data_soortenKenmerken (afdwingen door error zodat we zeker zijn dat het eindresultaat juist is)
- Warning geven als de vegetatielaag niet ingevuld is bij een van de soorten (waardoor we de verantwoordelijkheid bij de gebruiker leggen: hij kan die warning gemakkelijk negeren)
- Een andere optie is om bovenstaande error of warning enkel te geven wanneer het relevant is, dus bij het berekenen van een voorwaarde waarbij de vegetatielaag noodzakelijk is maar niet opgegeven is door de gebruiker.  Voordeel hiervan is dat er niet onnodig warnings of errors gegeven worden, nadeel is dat het voor de gebruiker minder duidelijk is: wanneer wel de vegetatielaag opgeven, en wanneer niet?

Wat denken jullie hiervan?

**Comment by ElsLommelen** [comment]
Ingeval van een warning moeten we trouwens ook bepalen hoe we de berekening uitvoeren:
- ofwel tellen we de soorten met vegetatielaag NA wel mee bij de berekening
- ofwel tellen we deze soorten niet mee, zoals nu het geval is

(voor de boomlaag vermoed ik dat het eerste resultaat het dichtst de werkelijkheid benadert omdat de bedekking van de boompjes in de kruidlaag vaak verwaarloosbaar is, voor boomsoorten in de kruidlaag lijkt de tweede optie een betere benadering ;-) )

**Comment by ToonHub** [comment]
een standaard vegetatieopname bevat ook de vegetatielaag, dus zou een error geven

**Comment by ElsLommelen** [comment]
En dit telkens als bij een soort geen vegetatielaag opgegeven is?  Of enkel waar het echt een probleem is?

**Comment by ToonHub** [comment]
Bij voorkeur enkel waar het een probleem is. Als dat niet te veel extra werk is voor jou.

**Comment by ElsLommelen** [comment]
Da's enkel kwestie van de foutmelding op de juiste plaats te zetten, lijkt mij.  ;-)

**Comment by hansvancalster** [comment]
Ik ben akkoord met jullie idee om foutmelding te geven op de specifieke plaats. 
Misschien ook een warning op globaal niveau want in principe moet bij elke vegetatie-opname de laag gekend zijn. Die warning zal enkel vergezeld zijn van een foutmelding indien het echt een probleem is voor de berekening.

**Comment by ElsLommelen** [comment]
Vermits dit issue intussen ingewerkt is in pull request #93, ga ik het issue alvast sluiten.
