### ISSUE TITLE
0 versus NA bij het ontbreken van soorten of kenmerken

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/LSVI#92]
(Ook weer een discussie-item)

Wanneer een voorwaarde niet ingevoerd wordt via Data_voorwaarden en er geen soorten of kenmerken worden opgegeven die voor de voorwaarde in kwestie relevant zijn, krijgt deze als Waarde 0.

Dit klopt voor soorten als je ervan uit gaat dat er een volopname gebeurd is, maar voor kenmerken (bv. aanwezige groeiklassen) is het misschien minder logisch dat deze sowieso in een opname vermeld zijn en dat deze als afwezig beschouwd worden als ze er niet tussen staan (eerder dan 'niet bekeken')?

Dus voorlopig verwacht de rekenmodule dat een gebruiker actief bij Data_voorwaarden NA invoert als bepaalde kenmerken (of soortenlijsten) niet (volledig) geobserveerd zijn.

Is dit logisch?  Kan het gemakkelijker voor de gebruiker (NA invoeren vraagt een grotere inspanning dan de berekening)?  Zien jullie een andere mogelijkheid om een onderscheid te maken tussen 0 en NA?  We zouden de gebruiker door een aparte parameter kunnen laten aangeven of het al dan niet over een volopname gaat, maar dat zegt dan nog niks over het al dan niet bekijken van die groeivormen of andere kenmerken...  Evt. NA als resultaat geven als er voor een bepaalde opname geen enkele soort (voor soortenlijst) of geen enkel kenmerk (voor studielijst) is opgegeven?  En dan 0 als er er minstens 1 soort (soortenlijst) of kenmerk (studielijst) is opgegeven dat niet relevant is voor de voorwaarde in kwestie?  Of voorgaande regel enkel voor soorten toepassen, en voor kenmerken NA geven tenzij het (of minstens een van de) kenmerk(en) in kwestie effectief in de lijst staat?  ...  Alle reacties en ideeën welkom!

**Comment by hansvancalster** [comment]
Al of niet volopname als parameter gaat niet werken. Het kan immers een gedeeltelijke opname zijn waar wel alle voor de LSVI te bepalen soorten/kenmerken ingeschat zijn. Ik vermoed dat het toch aan de gebruiker zal zijn om NA aan te geven.

**Comment by ElsLommelen** [comment]
En wat met het idee om bij kenmerken als groeivormen, ontwikkelingsstadia,... als resultaat voor de indicator NA te geven als deze niet in de opname staan, en 0 (of een bedekking) van zodra er eentje in de opname staat?

In tegenstelling tot soorten lijkt me voor kenmerken de kans groter dat deze niet opgenomen zijn in de lijst, en voor een gebruiker zou het weleens tamelijk wat werk kunnen zijn om alle indicatoren te overlopen en aan te duiden wat ze niet bekeken hebben (als ik een grote heterogene dataset uit INBOVEG in gedachten heb).  Voor mij lijkt het hier logischer dat ze aangeven wat ze wel bekeken hebben, eerder dan wat ze niet bekeken hebben.

Voor soorten ok om ervan uit te gaan dat ze een volopname gemaakt hebben ofwel actief aanduiden welke indicatoren ze niet bekeken hebben (dus situatie behouden zoals ze is).

Misschien iets minder logisch om soorten en kenmerken in dit opzicht verschillend te behandelen, maar anderzijds lijkt het me zo wel dichter bij de praktijk aan te sluiten.

(Reageer zeker als jullie er anders over denken, jullie hebben meer voeling met de data zelf!)

**Comment by ToonSpanhoveINBO** [comment]
Wat soorten betreft lijken me 3 scenario's mogelijk
1) een volledige opname & niet vermelde soorten zijn ook afwezig -> aanduiden als 'volopname'
2) er is enkel gekeken naar een beperkte set soorten. afwezige soorten moeten dan wel ingevoerd worden met bedekking 0 . Voor de data in de LSVI app vergt dit nog wat werk, maar dit is alleszins te reconstrueren. Het invoeren van 'nulwaarnemingen' heeft ook het voordeel dat er bij wijzigingen van soortenlijsten kan nagegaan worden of er wel naar alle soorten werd gekeken...
3) soortenlijst is onvolledig, met beperkte waarde voor LSVI bepaling (meestal 'eenzijdige' uitspraak mogelijk)

**Comment by ToonSpanhoveINBO** [comment]
Het voorstel om NA weer te geven indien die andere kenmerken (ouderdom struikhei, groeiklasse,...) totaal niet voorkomen lijkt me prima.

**Comment by ElsLommelen** [comment]
soorten: van uit gaan dat er een volopname gebeurd is, dus 0 van zodra er 1 soort ingevoerd is
andere kenmerken: standaard NA, maar voor groeiklassen e.d. wel 0 zodra er eentje  voorkomt
