### ISSUE TITLE
soortenlijst 4030 versie 2 voorwaarde 'aantal sleutelsoorten' niet OK

### ISSUE THREAD

**Issue by ToonHub** [inbo/LSVI#95]
de soortenlijst bevat nog struikheide, maar die moet eruit
bij versie 3 van 4030 is het wel OK
@ElsLommelen : kan je eens nakijken

**Comment by ElsLommelen** [comment]
Nagekeken en opgelost in de csv, en die bezorg ik seffens aan Gert..

**Comment by ElsLommelen** [comment]
Dit zou morgen in orde moeten zijn, check je dit even en sluit je dan het issue?

**Comment by ToonHub** [comment]
In orde
